# Copyright Altran Netherlands B.V
stages:
  - build
  - check
  - test
  - publish
  - smoke
  - acceptance
  - performance
  - manual
  - release

variables:
  REGISTRY_URL: registry.acidspace.nl
  MAVEN_CONTAINER: acid/container/maven:0.36.0
  
  # Cache downloaded dependencies and plugins between builds
  MAVEN_REPO: '.m2/repository'
  MAVEN_OPTS: '-Dmaven.repo.local=$MAVEN_REPO -Xmx2048m'

cache:
  key: '$CI_JOB_NAME'
  paths:
    - '$MAVEN_REPO'

mde-build:
  image: ${REGISTRY_URL}/${MAVEN_CONTAINER}
  stage: build
  tags:
    - linux_docker
  script:
    - acidcli build binaries
  artifacts:
    when: always
    paths:
      - reports/build/binaries
      # These outputs should be used as input in other build stages
      # P2 repository
      - 'releng/*/target/repository/*'
      # Built jars
      - 'code/com.altran.general.emf.ecoredoc.standalone/target/*.jar'
      # Documentation
      - 'plugins/com.altran.general.emf.ecoredoc.guide.user/target/pages'
    expire_in: 1 week

mde-unit-test:
  image: ${REGISTRY_URL}/${MAVEN_CONTAINER}
  stage: test
  # Maven unit-test do not depend on build as they re-build the code, 
  # so start asap, hence empty needs
  needs: []
  tags:
    - linux_docker_medium
  variables:
    DISPLAY: ':99'
  before_script:
    # You can start a virtual display (XVFB frame buffer) if required
    - Xvfb ${DISPLAY} -screen 0 1280x1024x16 -nolisten tcp &
  script:
    - acidcli test units
  artifacts:
    when: always
    paths:
      - reports/test/units/
      - '*/*/target/invoker-reports/'
      - '*/*/target/it/*/build.log'
      - '*/*/target/it/*/*.adoc'
    reports:
      junit: '*/*/target/surefire-reports/*.xml'
    expire_in: 4 weeks

mvn-deploy:
  image: ${REGISTRY_URL}/${MAVEN_CONTAINER}
  stage: release
  tags:
    - linux_docker
  only:
    - develop
    - tags
  script:
    - mvn deploy -Dmaven.test.skip=true -s settings.xml

mde-release:
  image: ${REGISTRY_URL}/${MAVEN_CONTAINER}
  stage: release
  # MDE release needs the artifacts from mde-build to be deployed
  dependencies: [mde-build]
  only:
    - develop
    - tags
  tags:
    - linux_docker
  script:
    - acidcli release binaries
  artifacts:
    when: always
    paths:
      - reports/release/binaries
    expire_in: 4 weeks
    
pages:
  stage: publish
  # Pages needs the artifacts from mvn-build
  dependencies: [mde-build]
  tags:
    - linux_docker
  only:
    - develop
  script:
    - cp -R plugins/com.altran.general.emf.ecoredoc.guide.user/target/pages/ public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
