<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EPackage2" nsURI="http://altran.com/general/emf/ecoredoc/test/epackage2/1.0.0"
    nsPrefix="ep2">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Package2 documentation"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SomeClass" eSuperTypes="EPackage1.ecore#//EClass1 EPackage1.ecore#//Iface">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is&#xD;&#xA;&#xD;&#xA;my doc"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class3">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="2.71"/>
  </eClassifiers>
</ecore:EPackage>
